name: Publish JSR

on:
  push:
    branches:
      - main

jobs:

  publish:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1

      - run: deno publish

